muqss: Add missing static function, uclamp_is_used
Fix build error after stable patches below was merged:
 - sched/uclamp: Protect uclamp fast path code with static key

Build error:

kernel/sched/cpufreq_schedutil.c: In function ‘schedutil_cpu_util’:
kernel/sched/cpufreq_schedutil.c:219:7: error: implicit declaration of function ‘uclamp_is_used’ [-Werror=implicit-function-declaration]
  219 |  if (!uclamp_is_used() &&
      |       ^~~~~~~~~~~~~~

(cherry picked from commit e7113f2c1d56962d4afabc627ad761c138f5b858)